import {
  ScatterChart,
  Filter,
  Palette,
  Search,
  Download,
  Share2,
  Map,
  ExternalLink,
  Image,
  Info,
  AlertTriangle,
  CheckCircle2,
  CircleX,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  RotateCcw,
  LayoutGrid,
  Dna,
  HeartPulse,
  Layers,
  Fingerprint,
  PieChart,
  ShieldCheck,
  Users,
  BarChart3,
  Table,
  Database,
  Microscope,
  Clock,
  Activity,
  Eye,
  GitBranch,
  GitFork,
  Globe,
  FlaskConical,
  Waypoints,
  Hash,
  Workflow,
  BookOpen,
  TrendingUp,
  TrendingDown,
  ArrowUp,
  ArrowDown,
  Clipboard,
  Check,
  User,
  MousePointerClick,
  X,
  SlidersHorizontal,
  Flame,
  Quote,
  Grid3x3,
} from 'lucide-react';
import type { LucideProps } from 'lucide-react';

const ICON_MAP = {
  'scatter-chart': ScatterChart,
  filter: Filter,
  palette: Palette,
  search: Search,
  download: Download,
  share: Share2,
  map: Map,
  'external-link': ExternalLink,
  image: Image,
  info: Info,
  warning: AlertTriangle,
  'check-circle': CheckCircle2,
  'circle-x': CircleX,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-down': ArrowUpDown,
  'rotate-ccw': RotateCcw,
  'layout-grid': LayoutGrid,
  dna: Dna,
  'heart-pulse': HeartPulse,
  layers: Layers,
  fingerprint: Fingerprint,
  'pie-chart': PieChart,
  'shield-check': ShieldCheck,
  users: Users,
  'bar-chart': BarChart3,
  table: Table,
  database: Database,
  microscope: Microscope,
  clock: Clock,
  activity: Activity,
  eye: Eye,
  'git-branch': GitBranch,
  'git-fork': GitFork,
  globe: Globe,
  'flask-conical': FlaskConical,
  waypoints: Waypoints,
  hash: Hash,
  workflow: Workflow,
  'book-open': BookOpen,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  clipboard: Clipboard,
  check: Check,
  user: User,
  'mouse-pointer-click': MousePointerClick,
  x: X,
  'sliders-horizontal': SlidersHorizontal,
  flame: Flame,
  quote: Quote,
  'grid-3x3': Grid3x3,
} as const;

export type IconName = keyof typeof ICON_MAP;

interface IconProps extends Omit<LucideProps, 'ref'> {
  name: IconName;
}

export function Icon({ name, ...props }: IconProps) {
  const Component = ICON_MAP[name];
  return <Component aria-hidden="true" {...props} />;
}
