"""Download outlier slides from GDC portal for visual inspection.

Reads the GDC file mapping generated by the EDA notebook and downloads
each SVS file using the GDC Data Transfer API. Supports resuming
interrupted downloads.

Usage:
    uv run python scripts/data/download_outlier_slides.py
"""

import json
import logging
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import requests

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

GDC_DATA_URL = "https://api.gdc.cancer.gov/data"
MAPPING_PATH = Path("data/outlier_slides_gdc_mapping.json")
OUTPUT_DIR = Path.home() / "Documents" / "tcga_slides"
MAX_WORKERS = 4
CHUNK_SIZE = 8 * 1024 * 1024  # 8 MB chunks


def download_slide(file_id: str, file_name: str, expected_size_mb: float) -> str:
    """Download a single slide from GDC. Skips if already downloaded."""
    output_path = OUTPUT_DIR / file_name

    # Skip if already fully downloaded
    if output_path.exists():
        actual_size = output_path.stat().st_size
        expected_bytes = int(expected_size_mb * 1e6)
        # Allow 1% tolerance for size rounding
        if actual_size > expected_bytes * 0.99:
            return f"SKIP  {file_name} (already downloaded, {actual_size / 1e6:.1f} MB)"

    url = f"{GDC_DATA_URL}/{file_id}"
    try:
        resp = requests.get(url, stream=True, timeout=600)
        resp.raise_for_status()

        total = int(resp.headers.get("content-length", 0))
        downloaded = 0

        with open(output_path, "wb") as f:
            for chunk in resp.iter_content(chunk_size=CHUNK_SIZE):
                f.write(chunk)
                downloaded += len(chunk)

        size_mb = downloaded / 1e6
        return f"OK    {file_name} ({size_mb:.1f} MB)"

    except Exception as e:
        # Clean up partial download
        if output_path.exists():
            output_path.unlink()
        return f"FAIL  {file_name}: {e}"


def main() -> None:
    if not MAPPING_PATH.exists():
        logger.error(f"Mapping file not found: {MAPPING_PATH}")
        logger.error("Run the EDA notebook first to generate the GDC mapping.")
        sys.exit(1)

    with open(MAPPING_PATH) as f:
        mapping = json.load(f)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    total_size_gb = sum(m["file_size_mb"] for m in mapping) / 1000
    logger.info(f"Downloading {len(mapping)} slides ({total_size_gb:.1f} GB) to {OUTPUT_DIR}")
    logger.info(f"Using {MAX_WORKERS} parallel workers")

    completed = 0
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {
            executor.submit(
                download_slide,
                m["file_id"],
                m["file_name"],
                m["file_size_mb"],
            ): m["file_name"]
            for m in mapping
        }

        for future in as_completed(futures):
            completed += 1
            result = future.result()
            logger.info(f"[{completed}/{len(mapping)}] {result}")

    # Summary
    downloaded = list(OUTPUT_DIR.glob("*.svs"))
    total_downloaded_gb = sum(f.stat().st_size for f in downloaded) / 1e9
    logger.info(f"\nDone: {len(downloaded)} slides, {total_downloaded_gb:.1f} GB in {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
